# Use MongoDB, Redis and the Dockerfile of ./backend to build the image
version: '3.7'

services:
  database:
    image: mongo:latest
    container_name: database
    restart: always
    ports:
      - 27018:27017
    volumes:
      - ./data:/data/db
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6380:6379
    networks:
      - backend

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 5000:8080
    networks:
      - backend
    depends_on:
      - database
      - redis
    # environment:
    #   - GIN_MODE=release

networks:
  backend:
    driver: bridge
