database:
  type: MongoDB
  name: cmsDB

server:
  port: 8080

logging:
  level: information
  port: 8081

authentication:
  token_expire_minutes: 60
  redis_address: localhost:6379
  redis_password: ""
  redis_db: 0
