database:
  type: MongoDB
  name: cmsDB
  connect: mongodb://database:27017

server:
  port: 8080

logging:
  level: information
  port: 8081

authentication:
  token_expire_minutes: 60
  redis_address: redis:6379
  redis_password: ""
  redis_db: 0
