import { cookies, headers } from "next/headers";
import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { Inter } from "next/font/google";
import { Providers } from "@/utils/providers";
import { AppNavigation } from "@/components/AppNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

async function checkAuth() {
    const cookie = cookies().get("jwt");
    return cookie;
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const headersList = headers();
    const url = headersList.get("x-url") || "";
    // only redirect, if not on login page. Else we get an infinite loop
    if (!url.includes("login")) {
        const check = await checkAuth();
        if (!check) redirect("/auth/login");
    }

    if (url.includes("login"))
        return (
            <html lang="en">
                <Providers>
                    <body className={inter.className}>{children}</body>
                </Providers>
            </html>
        );

    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <AppNavigation>{children}</AppNavigation>
                </Providers>
            </body>
        </html>
    );
}

